name: CI
on: 
   push:
      branches:
         - devel
         - master
         - testing*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build dist
      run: |
         sudo apt-get update
         sudo apt-get -y install avr-libc
         REV=$(git rev-parse --short HEAD | tr a-z A-Z)
         VER=94
         PLUS=+
         make CONFIG=configs/config-petSD+ PRERELEASE=ATENTDEAD0-${VER}${PLUS}-$REV
         mkdir bin
         cp obj-m1284p-petSD+/NODISKEMU.bin bin/sd2iec-1.0.0atentdead0-${VER}${PLUS}-$REV-petSD+.bin

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sd2iec-firmware
        path: bin/
