name: Release
on: 
   push:
      tags:
         - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build dist
      id: build
      run: |
      run: |
         sudo apt-get update
         sudo apt-get -y install avr-libc
         REV=$(git rev-parse --short HEAD | tr a-z A-Z)
         VER=94
         PLUS=+
         make CONFIG=configs/config-petSD+ PRERELEASE=ATENTDEAD0-${VER}${PLUS}-$REV
         mkdir bin
         cp obj-m1284p-petSD+/NODISKEMU.bin bin/sd2iec-1.0.0atentdead0-${VER}${PLUS}-$REV-petSD+.bin
         cd bin
         zip ../sd2iec-firmware-1.0.0atentdead0-${VER}${PLUS}-$REV.zip sd2iec*
         cd ..

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
         files: sd2iec-firmware-${{ steps.build.outputs.ver }}.zip
         draft: true
         prerelease: false
         name: SD2IEC Firmware ${{ steps.build.outputs.ver }}
         generate_release_notes: false
         body: To be done.
