name: Release
on: 
   push:
      tags:
         - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build dist
      id: build
      run: |
         sudo apt-get update
         sudo apt-get -y install avr-libc
         REV=$(git rev-parse --short HEAD | tr a-z A-Z)
         VER=63
         PLUS=+
         echo "ver=1.0.0atentdead0-${VER}${PLUS}-$REV" >> $GITHUB_OUTPUT
         make CONFIG=configs/config-uIEC PRERELEASE=ATENTDEAD0-${VER}${PLUS}-$REV
         make CONFIG=configs/config-uIEC3 PRERELEASE=ATENTDEAD0-${VER}${PLUS}-$REV
         make CONFIG=configs/config-larsp PRERELEASE=ATENTDEAD0-${VER}${PLUS}-$REV
         make CONFIG=configs/config-sw1 PRERELEASE=ATENTDEAD0-${VER}${PLUS}-$REV
         make CONFIG=configs/config-sw2 PRERELEASE=ATENTDEAD0-${VER}${PLUS}-$REV
         mkdir bin
         cp obj-m1281-uIEC/sd2iec.bin bin/sd2iec-1.0.0atentdead0-${VER}${PLUS}-$REV-m1281-uIEC.bin
         cp obj-m1281-uIEC3/sd2iec.bin bin/sd2iec-1.0.0atentdead0-${VER}${PLUS}-$REV-m1281-uIEC3.bin
         cp obj-m1284p-larsp/sd2iec.bin bin/sd2iec-1.0.0atentdead0-${VER}${PLUS}-$REV-m1284p-larsp.bin
         cp obj-m1284p-sw1/sd2iec.bin bin/sd2iec-1.0.0atentdead0-${VER}${PLUS}-$REV-m1284p-sw1.bin
         cp obj-m1284p-sw2/sd2iec.bin bin/sd2iec-1.0.0atentdead0-${VER}${PLUS}-$REV-m1284p-sw2.bin
         cd bin
         zip ../sd2iec-firmware-1.0.0atentdead0-${VER}${PLUS}-$REV.zip sd2iec*
         cd ..

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
         files: sd2iec-firmware-${{ steps.build.outputs.ver }}.zip
         draft: true
         prerelease: false
         name: SD2IEC Firmware ${{ steps.build.outputs.ver }}
         generate_release_notes: false
         body: To be done.